### ISSUE TITLE
Upload point cloud results

### ISSUE THREAD

**Issue by DingYikang** [ToughStoneX/U-MVS#7]
Hi,

Thanks for your nice work. Could you please upload your point cloud results (DTU & TnT, or DTU only)? It seems the reproduced results are not so good.

Thanks a lot!

**Comment by ToughStoneX** [comment]
Sorry for the late response.
Here are the point cloud results generated on my server: [DTU](https://mogface.oss-cn-zhangjiakou.aliyuncs.com/xhb/share/umvs_iccv/dtu_point_clouds/eval_ply.tar.gz) (about 13G) and [T&T](https://mogface.oss-cn-zhangjiakou.aliyuncs.com/xhb/share/umvs_iccv/tanks_point_clouds/upload-20210311.tar.gz) (about 10G).

**Comment by DingYikang** [comment]
Tanks for your kind response, I appreciate it a lot!
